### ISSUE TITLE
Read Default Language?

### ISSUE THREAD

**Issue by JimLynchCodes** [0crispy/bevy_easy_localize#6]
Hey, I like this!

The simplicity of it is great, and the screenshot of the spreadsheet is perfect. Not even joking! 👌

Just wondering I we _need_ to set the default language, or if this can be automatically detected by the browser (wasm) / or native libs?

Thanks 👍

**Comment by 0crispy** [comment]
Thanks for your feedback! The default language is set manually for now, but you can easily extend this to automatically detect the language, either using native libraries (e.g., sys-locale for desktop) or browser APIs (for wasm, using navigator.language). I've added an example for use with `sys-locale` [here](https://github.com/0crispy/bevy_easy_localize/blob/master/examples/sys_locale.rs#L16-L23).
